In [1]:
#Q.1- What is the probability of a person playing when the weather is sunny? Find P(Yes|Sunny).

In [2]:
def pro(Y,S):
    
    pbSY = 3/9
    pbSN = 2/5
    
    pEYS = (pbSY*Y)/(S)
    
    return (pEYS)

pro(9/14,5/14)

0.6

In [3]:
#Q.2- Solve the following:

#a) Import iris dataset from sklearn.

In [13]:
# Import data and modules
import numpy as np
from sklearn import datasets

iris = datasets.load_iris()

In [15]:
type(iris)

sklearn.utils.Bunch

In [12]:
#b) Split the dataset into training and testing sets using train_test_split()

In [17]:
X = iris.data[:, [2, 3]]
y = iris.target

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)


In [22]:
X.shape

(150, 2)

In [25]:
#c) Use GaussianNB and print the following:
#i. Confusion matrix
#ii. Classification report



In [27]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics


In [30]:
#fit a navie bayes model to the data

model = GaussianNB()
model.fit(iris.data,iris.target)
print(model)

#make predictions

expected = iris.target
predicted = model.predict(iris.data)

#summarize the fit of the model

print(metrics.accuracy_score(expected,predicted))
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

GaussianNB(priors=None)
0.96
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.94      0.94      0.94        50
          2       0.94      0.94      0.94        50

avg / total       0.96      0.96      0.96       150

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]


In [32]:
# d) Use MultinomialNB and print the following:
#i. Confusion matrix
#ii. Classification report

In [ ]:
#fit a navie bayes model to the data

model = GaussianNB()
model.fit(iris.data,iris.target)
print(model)

#make predictions

expected = iris.target
predicted = model.predict(iris.data)

#summarize the fit of the model

print(metrics.accuracy_score(expected,predicted))
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))