In [9]:
#Q.1 Import MNIST dataset from sklearn. Save data and targets in variables X and Y respectively.


import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv('mnist.csv')

In [12]:
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [13]:
X = df.iloc[:,1:].values
y = df.iloc[:,0].values

In [14]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [16]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_

In [17]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [18]:
from sklearn import metrics

y_pred = classifier.predict(X_test)

print(metrics.accuracy_score(y_test,y_pred))
print(metrics.classification_report(y_test,y_pred))
print(metrics.confusion_matrix(y_test,y_pred))

0.4355952380952381
             precision    recall  f1-score   support

          0       0.54      0.84      0.66       813
          1       0.77      0.97      0.86       961
          2       0.25      0.06      0.10       860
          3       0.40      0.66      0.50       863
          4       0.39      0.37      0.38       827
          5       0.00      0.00      0.00       756
          6       0.30      0.31      0.30       841
          7       0.38      0.64      0.48       899
          8       0.25      0.27      0.26       768
          9       0.26      0.09      0.13       812

avg / total       0.36      0.44      0.38      8400

[[686   0  15  27   3   0  66   0  14   2]
 [  0 933   0  11   0   0   2   4  11   0]
 [123  47  55 340  10   0 135  25 119   6]
 [ 41  34  30 573   8   0  49  18 103   7]
 [ 23  22   0   0 303   0  27 357  12  83]
 [106  32  47 161  27   0 150  43 169  21]
 [191  31  40  88  55   0 258  17 151  10]
 [  6  48   0   2 160   0  15 575  21  72

C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
